server:
  port: 8066
  servlet:
    context-path: /idealagent/api/v1

spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ideal_agent?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    pgvector:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/ideal_agent
      username: idealagent
      password: 123456
